"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type CartItem={id:string;name:string;price:string;currency:string;image?:string;quantity:number};
type Shipping={method:"dpd_pickup"|"dpd_courier";pickupCode:string;pickupName:string;street:string;postalCode:string;city:string};
type Customer={name:string;company:string;nip:string;phone:string;email:string;street:string;postalCode:string;city:string;notes:string;invoice:boolean};
const KEY="widia-cart"; const empty:Customer={name:"",company:"",nip:"",phone:"",email:"",street:"",postalCode:"",city:"",notes:"",invoice:false};
export default function CartPage(){
 const [items,setItems]=useState<CartItem[]>([]),[customer,setCustomer]=useState(empty),[shipping,setShipping]=useState<Shipping>({method:"dpd_courier",pickupCode:"",pickupName:"",street:"",postalCode:"",city:""}),[sending,setSending]=useState(false),[result,setResult]=useState<string|null>(null),[error,setError]=useState("");
 const [accepted,setAccepted]=useState(false);
 useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(KEY)||"[]"));}catch{}},[]);
 const persist=(next:CartItem[])=>{setItems(next);localStorage.setItem(KEY,JSON.stringify(next));window.dispatchEvent(new Event("widia-cart-updated"));};
 const total=useMemo(()=>items.reduce((s,i)=>s+(Number.parseFloat(i.price.replace(",","."))||0)*i.quantity,0),[items]);
 async function submit(e:FormEvent){e.preventDefault();if(!items.length)return; if(shipping.method==="dpd_pickup"&&!shipping.pickupCode){setError("Wybierz punkt DPD Pickup.");return;} setSending(true);setError("");try{const res=await fetch("/api/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:items.map(({id,quantity})=>({id,quantity})),customer,payment:"cash_on_delivery",shipping,accepted})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Nie udało się złożyć zamówienia.");setResult(data.orderNumber);persist([]);}catch(err){setError(err instanceof Error?err.message:"Błąd zamówienia.");}finally{setSending(false);}}
 if(result)return <main className="min-h-screen bg-zinc-100 p-6"><section className="mx-auto mt-10 max-w-xl rounded-3xl bg-white p-8 text-center shadow"><div className="text-5xl">✓</div><h1 className="mt-4 text-3xl font-black">Zamówienie przyjęte</h1><p className="mt-3">Numer zamówienia: <b>{result}</b></p><p className="mt-4 text-zinc-600">Dostawa DPD jest bezpłatna. Skontaktujemy się telefonicznie, aby potwierdzić szczegóły.</p><a href="/" className="mt-6 inline-flex rounded-full bg-zinc-950 px-6 py-3 font-bold text-white">Wróć do katalogu</a></section></main>;
 return <main className="min-h-screen bg-zinc-100 px-4 py-8 text-zinc-950"><div className="mx-auto max-w-6xl"><a href="/" className="font-bold text-zinc-500">← Wróć do katalogu</a><h1 className="mt-4 text-4xl font-black">Koszyk</h1>{!items.length?<div className="mt-8 rounded-3xl bg-white p-8 font-bold">Koszyk jest pusty.</div>:<form onSubmit={submit} className="mt-8 grid gap-6 lg:grid-cols-[1fr_1fr]">
 <section className="rounded-3xl bg-white p-5 shadow sm:p-7"><h2 className="text-2xl font-black">Produkty</h2><div className="mt-5 grid gap-3">{items.map(i=><article key={i.id} className="flex gap-3 rounded-2xl border p-3">{i.image?<img src={i.image} alt="" className="h-20 w-20 rounded-xl object-contain"/>:<div className="h-20 w-20 rounded-xl bg-zinc-100"/>}<div className="min-w-0"><h3 className="font-bold">{i.name}</h3><p className="font-black text-green-700">{i.price} {i.currency} × {i.quantity}</p><div className="mt-2 flex gap-2"><button type="button" className="rounded-full border px-3" onClick={()=>persist(items.map(x=>x.id===i.id?{...x,quantity:Math.max(1,x.quantity-1)}:x))}>−</button><button type="button" className="rounded-full border px-3" onClick={()=>persist(items.map(x=>x.id===i.id?{...x,quantity:x.quantity+1}:x))}>+</button><button type="button" className="text-xs font-bold text-red-600" onClick={()=>persist(items.filter(x=>x.id!==i.id))}>Usuń</button></div></div></article>)}</div><p className="mt-6 border-t pt-4 text-right text-2xl font-black">Razem: {total.toFixed(2)} PLN</p><div className="mt-4 rounded-2xl border-2 border-green-400 bg-green-50 p-4 font-black">DARMOWA DOSTAWA DPD</div></section>
 <section className="rounded-3xl bg-white p-5 shadow sm:p-7"><h2 className="text-2xl font-black">Dostawa DPD</h2><div className="mt-4 grid gap-3"><label className="flex cursor-pointer gap-3 rounded-2xl border p-4"><input type="radio" checked={shipping.method==="dpd_pickup"} onChange={()=>setShipping({...shipping,method:"dpd_pickup"})}/><span><b>DPD Pickup — punkt odbioru</b><small className="block text-zinc-500">Wybierz punkt na mapie. Dostawa 0 zł.</small></span></label><label className="flex cursor-pointer gap-3 rounded-2xl border p-4"><input type="radio" checked={shipping.method==="dpd_courier"} onChange={()=>setShipping({...shipping,method:"dpd_courier"})}/><span><b>DPD Kurier — dostawa na adres</b><small className="block text-zinc-500">Kurier DPD pod wskazany adres. Dostawa 0 zł.</small></span></label>{shipping.method==="dpd_pickup"?<div className="rounded-2xl bg-zinc-50 p-4"><p className="text-sm font-bold">Wybierz punkt DPD lub paczkomat na oficjalnej mapie.</p><a href="https://www.dpd.com/pl/pl/dpd-pickup/znajdz-punkt-dpd-pickup/" target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex rounded-xl bg-zinc-900 px-4 py-3 text-sm font-bold text-white">Otwórz oficjalną mapę DPD</a><label className="mt-3 block text-sm font-bold">Kod punktu DPD / numer automatu<input required placeholder="np. WAW123M" value={shipping.pickupCode} onChange={e=>setShipping({...shipping,pickupCode:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-3 font-normal"/></label>{shipping.pickupName&&<p className="mt-3 rounded-xl border border-green-300 bg-green-50 p-3 text-sm"><b>Wybrano:</b> {shipping.pickupName}</p>}<p className="mt-2 text-xs text-zinc-500">Po wyborze na mapie wpisz kod punktu lub numer automatu powyżej.</p></div>:<div className="grid gap-3"><input required placeholder="Ulica i numer" value={shipping.street} onChange={e=>setShipping({...shipping,street:e.target.value})} className="rounded-xl border px-3 py-3"/><div className="grid grid-cols-[130px_1fr] gap-3"><input required placeholder="Kod pocztowy" value={shipping.postalCode} onChange={e=>setShipping({...shipping,postalCode:e.target.value})} className="rounded-xl border px-3 py-3"/><input required placeholder="Miejscowość" value={shipping.city} onChange={e=>setShipping({...shipping,city:e.target.value})} className="rounded-xl border px-3 py-3"/></div></div>}</div>
 <h2 className="mt-7 text-2xl font-black">Dane kupującego</h2><div className="mt-4 grid gap-3"><input required placeholder="Imię i nazwisko" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})} className="rounded-xl border px-3 py-3"/><input required type="tel" placeholder="Telefon" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})} className="rounded-xl border px-3 py-3"/><input required type="email" placeholder="E-mail" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})} className="rounded-xl border px-3 py-3"/><input required placeholder="Ulica i numer (adres rozliczeniowy)" value={customer.street} onChange={e=>setCustomer({...customer,street:e.target.value})} className="rounded-xl border px-3 py-3"/><div className="grid grid-cols-[130px_1fr] gap-3"><input required placeholder="Kod pocztowy" value={customer.postalCode} onChange={e=>setCustomer({...customer,postalCode:e.target.value})} className="rounded-xl border px-3 py-3"/><input required placeholder="Miejscowość" value={customer.city} onChange={e=>setCustomer({...customer,city:e.target.value})} className="rounded-xl border px-3 py-3"/></div><textarea placeholder="Uwagi" value={customer.notes} onChange={e=>setCustomer({...customer,notes:e.target.value})} className="min-h-20 rounded-xl border px-3 py-3"/><div className="rounded-2xl bg-zinc-50 p-3 text-sm">Płatność: za pobraniem. Zapłacisz kurierowi przy odbiorze.</div><label className="flex cursor-pointer gap-2 rounded-xl border p-3 text-xs"><input required type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} className="mt-0.5 h-4 w-4"/><span>Akceptuję <a href="/regulamin" target="_blank" className="font-bold underline">Regulamin</a> i <a href="/polityka-prywatnosci" target="_blank" className="font-bold underline">Politykę prywatności</a>.</span></label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<button disabled={sending} className="rounded-full bg-green-600 px-6 py-4 text-lg font-black text-white disabled:opacity-50">{sending?"Wysyłanie...":"Zamawiam z darmową dostawą DPD"}</button></div></section>
 </form>}</div></main>;
}