import type { Metadata } from "next";

export const metadata: Metadata = { title: "Regulamin sklepu", description: "Regulamin sklepu internetowego Widia.tech.eu.", alternates: { canonical: "/regulamin" } };

export default function TermsPage() {
  return <main className="min-h-screen bg-zinc-100 px-4 py-8 text-zinc-950 sm:px-6 sm:py-12"><article className="mx-auto max-w-4xl rounded-3xl bg-white p-6 shadow-sm sm:p-10"><a href="/" className="text-sm font-bold text-zinc-500">← Strona główna</a><h1 className="mt-6 text-4xl font-black">Regulamin sklepu Widia.tech.eu</h1><p className="mt-3 text-sm text-zinc-500">Obowiązuje od 30.08.2026 r.</p>
  <h2 className="mt-8 text-2xl font-black">1. Sprzedawca i kontakt</h2><p className="mt-3 leading-7 text-zinc-700">Sklep internetowy Widia.tech.eu jest prowadzony przez Ekogratis sp. z o.o., Jagielska 25/27, 02-886 Warszawa, Polska. Kontakt: tel. +48 512 077 770, e-mail: info@widia.tech. Dane rejestrowe spółki udostępniane są zgodnie z obowiązującymi przepisami.</p>
  <h2 className="mt-8 text-2xl font-black">2. Zasady korzystania ze sklepu</h2><p className="mt-3 leading-7 text-zinc-700">Do korzystania ze sklepu potrzebne jest urządzenie z dostępem do Internetu, aktualna przeglądarka internetowa oraz aktywny adres e-mail. Zakup nie wymaga zakładania konta. Klient powinien podawać prawdziwe i kompletne dane niezbędne do realizacji zamówienia.</p>
  <h2 className="mt-8 text-2xl font-black">3. Towary i ceny</h2><p className="mt-3 leading-7 text-zinc-700">Informacje o towarach, ich cechach, cenach i dostępności znajdują się przy poszczególnych ofertach. Ceny prezentowane w sklepie są cenami brutto, jeżeli przy ofercie nie wskazano inaczej. Koszt dostawy jest podawany lub potwierdzany przed realizacją zamówienia, w szczególności w przypadku przesyłek gabarytowych i paletowych.</p>
  <h2 className="mt-8 text-2xl font-black">4. Składanie zamówienia</h2><p className="mt-3 leading-7 text-zinc-700">Klient wybiera towar i jego ilość, dodaje go do koszyka, podaje dane do dostawy, zapoznaje się z regulaminem i wymaganymi informacjami, a następnie składa zamówienie przyciskiem jednoznacznie wskazującym obowiązek zapłaty. Po przyjęciu zamówienia sklep nadaje mu numer i przesyła potwierdzenie na podany adres e-mail, jeżeli wysyłka wiadomości jest technicznie dostępna. Umowa sprzedaży zostaje zawarta po przyjęciu zamówienia przez Sprzedawcę do realizacji i potwierdzeniu jego warunków.</p>
  <h2 className="mt-8 text-2xl font-black">5. Płatność i dostawa</h2><p className="mt-3 leading-7 text-zinc-700">Dla zamówień składanych bezpośrednio w sklepie dostępna jest płatność za pobraniem, chyba że przy danym towarze uzgodniono inaczej. Zapłata następuje przewoźnikowi przy odbiorze. Sposób, koszt i termin dostawy zależą od rodzaju, gabarytu i masy towaru oraz adresu dostawy. Szczegóły opisuje strona „Dostawa”.</p>
  <h2 className="mt-8 text-2xl font-black">6. Prawo odstąpienia i 30-dniowy zwrot</h2><p className="mt-3 leading-7 text-zinc-700">Konsumentowi przysługuje ustawowe prawo odstąpienia od umowy zawartej na odległość w przypadkach i terminach określonych przepisami. Niezależnie od tego Widia.tech umożliwia zwrot towaru w terminie 30 dni od jego otrzymania na zasadach opisanych na stronie „Zwroty, reklamacje, gwarancja”. Dobrowolny 30-dniowy okres nie ogranicza praw konsumenta wynikających z ustawy. Jeżeli przepisy przewidują wyjątek od prawa odstąpienia, stosuje się odpowiedni wyjątek ustawowy.</p>
  <h2 className="mt-8 text-2xl font-black">7. Reklamacje</h2><p className="mt-3 leading-7 text-zinc-700">Sprzedawca odpowiada wobec konsumenta za zgodność towaru z umową na zasadach wynikających z obowiązujących przepisów. Reklamację można zgłosić na info@widia.tech lub telefonicznie pod numerem +48 512 077 770. W zgłoszeniu warto podać numer zamówienia, opis problemu i dane kontaktowe. Szczegółowe informacje znajdują się na stronie „Zwroty, reklamacje, gwarancja”.</p>
  <h2 className="mt-8 text-2xl font-black">8. Gwarancja</h2><p className="mt-3 leading-7 text-zinc-700">Widia.tech udziela 2-letniej gwarancji na produkty objęte ofertą sklepu. Okres gwarancji jest taki sam dla zakupu prywatnego i zakupu związanego z działalnością gospodarczą. Gwarancja nie ogranicza ani nie wyłącza praw kupującego wynikających z bezwzględnie obowiązujących przepisów.</p>
  <h2 className="mt-8 text-2xl font-black">9. Przedsiębiorcy</h2><p className="mt-3 leading-7 text-zinc-700">Postanowienia dotyczące szczególnych praw konsumenta stosuje się do przedsiębiorców tylko w zakresie, w jakim wynika to z obowiązujących przepisów. Dobrowolna 2-letnia gwarancja Widia.tech obowiązuje również przy zakupach firmowych zgodnie z jej warunkami.</p>
  <h2 className="mt-8 text-2xl font-black">10. Dane osobowe</h2><p className="mt-3 leading-7 text-zinc-700">Dane osobowe są przetwarzane w celu obsługi zamówień, realizacji umów, rozliczeń, reklamacji, gwarancji oraz wykonania obowiązków prawnych. Szczegółowe informacje znajdują się w Polityce prywatności i RODO.</p>
  <h2 className="mt-8 text-2xl font-black">11. Postanowienia końcowe</h2><p className="mt-3 leading-7 text-zinc-700">W sprawach nieuregulowanych regulaminem zastosowanie mają przepisy prawa polskiego oraz bezwzględnie obowiązujące przepisy prawa Unii Europejskiej. Regulamin nie wyłącza ani nie ogranicza praw konsumenta, których nie można wyłączyć umową. Aktualna wersja regulaminu jest dostępna na stronie sklepu.</p>
  <nav className="mt-10 flex flex-wrap gap-4 border-t pt-6 text-sm font-bold"><a href="/polityka-prywatnosci" className="text-green-700">Polityka prywatności i RODO →</a><a href="/zwroty-i-reklamacje">Zwroty, reklamacja, gwarancja</a><a href="/dostawa">Dostawa</a></nav></article></main>;
}
