import type { AllegroProduct } from "@/lib/allegro";
export type SeoCategory = { slug:string; keyword:string; title:string; description:string; heading:string; intro:string; terms:string[] };
export const seoCategories: SeoCategory[] = [
 {slug:"frez-nasadzany-prosty",keyword:"Frez nasadzany prosty",title:"Frez nasadzany prosty — Widia.tech",description:"Frezy nasadzane proste do profesjonalnej obróbki drewna.",heading:"Frez nasadzany prosty",intro:"Frezy nasadzane proste do warsztatu i produkcji mebli.",terms:["frez nasadzany","frez prosty","głowica frezarska","glowica frezarska"]},
 {slug:"frez-na-plytki-wymienne",keyword:"Frez na płytki wymienne",title:"Frez na płytki wymienne — Widia.tech",description:"Frezy na płytki wymienne do obróbki drewna.",heading:"Frez na płytki wymienne",intro:"Wymienne płytki zapewniają szybką i ekonomiczną pracę.",terms:["frez na płytki","frez na plytki","płytki wymienne","plytki wymienne"]},
 {slug:"frezy-kopiace",keyword:"Frezy kopiące",title:"Frezy kopiące — Widia.tech",description:"Frezy kopiące do precyzyjnej obróbki drewna.",heading:"Frezy kopiące",intro:"Frezy kopiące do rowków, gniazd i kształtowej obróbki drewna.",terms:["frez kopiący","frez kopiacy","frez do gniazd","frez rowkujący"]},
 {slug:"waly-spiralne",keyword:"Wały spiralne",title:"Wały spiralne — Widia.tech",description:"Wały spiralne i głowice spiralne do strugarek.",heading:"Wały spiralne",intro:"Wały spiralne do wydajnej obróbki drewna.",terms:["wał spiralny","wal spiralny","wały spiralne","wal spiralny"]},
 {slug:"strugi-rebir",keyword:"Strugi Rebir",title:"Strugi Rebir — Widia.tech",description:"Strugi Rebir do obróbki drewna.",heading:"Strugi Rebir",intro:"Strugi Rebir dla profesjonalistów i warsztatów.",terms:["strug rebir","rebir","strugarka rebir"]},
 {slug:"noze-do-gruboscio­wek",keyword:"Noże do grubościówek",title:"Noże do grubościówek — Widia.tech",description:"Noże do grubościówek i strugarek.",heading:"Noże do grubościówek",intro:"Noże zapewniają równe i czyste struganie drewna.",terms:["noże do grubościówek","noze do grubosciowek","grubościów","grubosciow"]},
 {slug:"inne",keyword:"Inne",title:"Inne narzędzia — Widia.tech",description:"Pozostałe narzędzia do obróbki drewna.",heading:"Inne",intro:"Pozostałe produkty Widia.tech.",terms:[]}
];
export function getSeoCategory(slug:string){return seoCategories.find(c=>c.slug===slug)??null;}
export function matchesSeoCategory(product:AllegroProduct,category:SeoCategory){const n=product.name.toLocaleLowerCase("pl-PL");return category.terms.length===0||category.terms.some(t=>n.includes(t.toLocaleLowerCase("pl-PL")));}
