import type { Metadata } from "next";

export const metadata: Metadata = { title: "Polityka prywatności i RODO", description: "Polityka prywatności i informacje RODO sklepu Widia.tech.eu.", alternates: { canonical: "/polityka-prywatnosci" } };

export default function PrivacyPage() {
  return <main className="min-h-screen bg-zinc-100 px-4 py-8 text-zinc-950 sm:px-6 sm:py-12"><article className="mx-auto max-w-4xl rounded-3xl bg-white p-6 shadow-sm sm:p-10"><a href="/" className="text-sm font-bold text-zinc-500">← Strona główna</a><h1 className="mt-6 text-4xl font-black">Polityka prywatności i RODO</h1><p className="mt-3 text-sm text-zinc-500">Obowiązuje od 30.08.2026 r.</p>
  <h2 className="mt-8 text-2xl font-black">1. Administrator danych</h2><p className="mt-3 leading-7 text-zinc-700">Administratorem danych osobowych przekazywanych w związku z korzystaniem ze sklepu Widia.tech.eu jest Ekogratis sp. z o.o., Jagielska 25/27, 02-886 Warszawa, Polska. Kontakt w sprawach dotyczących danych osobowych: info@widia.tech, tel. +48 512 077 770.</p>
  <h2 className="mt-8 text-2xl font-black">2. Jakie dane przetwarzamy</h2><p className="mt-3 leading-7 text-zinc-700">W zależności od sposobu korzystania ze sklepu możemy przetwarzać m.in. imię i nazwisko, nazwę firmy, NIP, adres dostawy i rozliczeniowy, numer telefonu, adres e-mail, informacje o zamówieniu, korespondencję dotyczącą zamówienia, reklamacji lub gwarancji oraz dane techniczne związane z korzystaniem ze strony.</p>
  <h2 className="mt-8 text-2xl font-black">3. Cele i podstawy przetwarzania</h2><div className="mt-3 space-y-3 leading-7 text-zinc-700"><p>Dane przetwarzamy w szczególności w celu przyjęcia i realizacji zamówienia oraz kontaktu w jego sprawie — gdy jest to niezbędne do zawarcia lub wykonania umowy (art. 6 ust. 1 lit. b RODO).</p><p>Dane związane z dokumentacją sprzedaży, podatkami i rachunkowością przetwarzamy w celu wykonania obowiązków prawnych (art. 6 ust. 1 lit. c RODO).</p><p>Dane dotyczące reklamacji, gwarancji, dochodzenia lub obrony roszczeń oraz zapewnienia bezpieczeństwa serwisu możemy przetwarzać na podstawie prawnie uzasadnionego interesu administratora (art. 6 ust. 1 lit. f RODO), o ile nie przeważają prawa i wolności osoby, której dane dotyczą.</p><p>Jeżeli określone przetwarzanie wymaga zgody, podstawą jest art. 6 ust. 1 lit. a RODO, a zgodę można wycofać w dowolnym momencie bez wpływu na zgodność z prawem wcześniejszego przetwarzania.</p></div>
  <h2 className="mt-8 text-2xl font-black">4. Odbiorcy danych</h2><p className="mt-3 leading-7 text-zinc-700">Dane mogą być przekazywane podmiotom, które pomagają nam prowadzić sklep i realizować zamówienia, w szczególności przewoźnikom, dostawcom hostingu i infrastruktury IT, dostawcom poczty elektronicznej, usług księgowych i prawnych oraz organom publicznym, gdy obowiązek przekazania danych wynika z prawa. Podmioty przetwarzające dane na nasze zlecenie otrzymują je wyłącznie w zakresie potrzebnym do świadczenia usług.</p>
  <h2 className="mt-8 text-2xl font-black">5. Przekazywanie danych poza EOG</h2><p className="mt-3 leading-7 text-zinc-700">Niektóre wykorzystywane usługi techniczne mogą wiązać się z przetwarzaniem danych poza Europejskim Obszarem Gospodarczym. W takim przypadku stosujemy mechanizmy wymagane przez RODO, odpowiednie do danego dostawcy i transferu, w szczególności decyzję stwierdzającą odpowiedni stopień ochrony lub standardowe klauzule umowne, jeżeli są wymagane.</p>
  <h2 className="mt-8 text-2xl font-black">6. Okres przechowywania</h2><p className="mt-3 leading-7 text-zinc-700">Dane związane z zamówieniem przechowujemy przez okres potrzebny do wykonania umowy, obsługi gwarancji i reklamacji, a następnie przez okres wymagany przepisami podatkowymi, rachunkowymi lub do upływu właściwych terminów przedawnienia roszczeń. Dane przetwarzane na podstawie zgody przechowujemy do jej wycofania lub wcześniejszego ustania celu przetwarzania, z uwzględnieniem obowiązków prawnych administratora.</p>
  <h2 className="mt-8 text-2xl font-black">7. Prawa osoby, której dane dotyczą</h2><p className="mt-3 leading-7 text-zinc-700">Na zasadach określonych w RODO przysługuje prawo dostępu do danych, ich sprostowania, usunięcia, ograniczenia przetwarzania, przenoszenia danych, wniesienia sprzeciwu wobec przetwarzania opartego na prawnie uzasadnionym interesie oraz wycofania zgody, jeżeli przetwarzanie odbywa się na jej podstawie. Przysługuje również prawo wniesienia skargi do Prezesa Urzędu Ochrony Danych Osobowych.</p>
  <h2 className="mt-8 text-2xl font-black">8. Czy podanie danych jest obowiązkowe</h2><p className="mt-3 leading-7 text-zinc-700">Podanie danych oznaczonych jako wymagane w formularzu zamówienia jest dobrowolne, ale niezbędne do przyjęcia i realizacji zamówienia. Brak tych danych uniemożliwi zawarcie lub wykonanie umowy. Dane do faktury są wymagane tylko wtedy, gdy klient żąda wystawienia dokumentu z odpowiednimi danymi.</p>
  <h2 className="mt-8 text-2xl font-black">9. Zautomatyzowane decyzje</h2><p className="mt-3 leading-7 text-zinc-700">Dane podawane w formularzu zamówienia nie są wykorzystywane przez Widia.tech do podejmowania wobec klienta decyzji wywołujących skutki prawne wyłącznie w sposób zautomatyzowany.</p>
  <h2 className="mt-8 text-2xl font-black">10. Pliki cookies i analityka</h2><p className="mt-3 leading-7 text-zinc-700">Strona może wykorzystywać pliki cookies lub podobne technologie niezbędne do działania serwisu, zapamiętania koszyka, bezpieczeństwa oraz — w zakresie dozwolonym prawem — pomiaru ruchu i statystyk. Koszyk jest zapisywany lokalnie w przeglądarce użytkownika. W przypadku technologii, które zgodnie z prawem wymagają uprzedniej zgody, powinny być one uruchamiane dopiero po jej uzyskaniu.</p>
  <h2 className="mt-8 text-2xl font-black">11. Kontakt</h2><p className="mt-3 leading-7 text-zinc-700">W sprawach dotyczących prywatności i realizacji praw wynikających z RODO można skontaktować się z nami pod adresem info@widia.tech lub telefonicznie: +48 512 077 770.</p>
  <nav className="mt-10 flex flex-wrap gap-4 border-t pt-6 text-sm font-bold"><a href="/regulamin" className="text-green-700">Regulamin sklepu →</a><a href="/zwroty-i-reklamacje">Zwroty, reklamacja, gwarancja</a><a href="/dostawa">Dostawa</a></nav></article></main>;
}
